### ISSUE TITLE
Design & Implement Card Mechanics

### ISSUE THREAD

**Issue by CallumDennisIE** [CallumDennisIE/2405-hackathon-team3#11]
Design Power - Defense - Force for cards / interactive functions

**Comment by Dimitris112** [comment]
Design Power - HP - Force (mana) for cards / interactive functions

**Comment by Dimitris112** [comment]
https://github.com/CallumDennisIE/2405-hackathon-team3/pull/19#issue-2313733391

**Comment by Dimitris112** [comment]
https://github.com/CallumDennisIE/2405-hackathon-team3/pull/19#issue-2313733391
