### ISSUE TITLE
Create Instructions

### ISSUE THREAD

**Issue by CallumDennisIE** [CallumDennisIE/2405-hackathon-team3#4]

**Comment by bhagyashriyogeshpatil** [comment]
### **Game Instructions**
**Objective:** The goal of the game is to win all the cards from your opponent.

**Setup:** 
1. Shuffle the deck of cards.
2. Distribute cards evenly between the player and the computer.

**How to Play:**
**1. Start the Game:**  Both players have a stack of facedown cards.
**2.Rounds:**
**•Player’s Turn:**
1.Player selects a stat from their top card.
2.Announces the chosen stat.
**•Computer’s Turn:**
1.Computer randomly selects a stat from its top card.
2.Reveals the selected stat.
**•Compare Stats:**
1.Reveal both top cards and compare stats.
2.Higher value wins the round.
**•Collect Cards:**
1.Winner takes both cards and places them at the bottom of their stack.
2.Winner starts the next round by selecting a stat from their new top card.

**End of the Game:**
•Game ends when a player runs out of cards (they lose).
**Additional Rules:**
•In case of a tie, cards go to a "tie pile." The next round's winner takes all the cards in the tie pile.
