### ISSUE TITLE
Create Main Page

### ISSUE THREAD

**Issue by CallumDennisIE** [CallumDennisIE/2405-hackathon-team3#7]

**Comment by bhagyashriyogeshpatil** [comment]
Create directory structure, add homepage image, implement homepage logic and add favicon

- Set up the initial directory structure for the project.
- Added an image for the homepage.
- Implemented the core logic for the homepage, including rendering the image.
- Implement main screen login, username verification, and modal instructions.
- Add favicon images and include favicon in homepage HTML
